/**
 * Auto-generated by scripts/generate-determinism-golden.ts — DO NOT EDIT.
 *
 * Hash of the full 1000-tick determinism scenario output
 * (frames + finalState). Any change to the render pipeline will
 * produce a different hash; regenerate after intentional changes.
 */

// Regenerate: pnpm --filter @europa/console exec tsx scripts/generate-determinism-golden.ts
export const GOLDEN_HASH = '314e1365449a4a5fad3c0207cee6d86a6322e291d0b5cd310eb3c40a64cd71b5';
export const GOLDEN_TICKS = 1000;
