/**
 * G-11 drift guard for contrast notes.
 *
 * Re-computes WCAG contrast ratios from the live token table and compares
 * against the checked-in `dist/contrast-notes.json`. If any ratio differs
 * the script exits 1 — the build output is stale and must be regenerated.
 *
 * If the file does not exist the script exits 0 with a warning (the file
 * is produced by the build step and may not yet be present in a fresh clone).
 */
import { readFile } from 'node:fs/promises';
import path from 'node:path';

import type { ContrastNote } from './generate-contrast-notes.js';
import { computeContrastNotes } from './generate-contrast-notes.js';

const PACKAGE_ROOT = path.resolve(import.meta.dirname, '..');
const CONTRAST_NOTES_PATH = path.join(PACKAGE_ROOT, 'dist', 'contrast-notes.json');

async function main(): Promise<void> {
    // If the file does not exist, warn and succeed — the build step produces it.
    let existing: ContrastNote[];
    try {
        const raw = await readFile(CONTRAST_NOTES_PATH, 'utf8');
        existing = JSON.parse(raw) as ContrastNote[];
    } catch (error: unknown) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
            process.stdout.write(
                'check-contrast-notes: dist/contrast-notes.json not found — skipping (generated by build)\n',
            );
            return;
        }
        throw error;
    }

    const computed = computeContrastNotes();

    // Build a lookup by pairing label for the stored notes.
    const storedByLabel = new Map<string, ContrastNote>();
    for (const note of existing) {
        storedByLabel.set(note.pairing, note);
    }

    const mismatches: string[] = [];

    for (const note of computed) {
        const stored = storedByLabel.get(note.pairing);
        if (stored === undefined) {
            mismatches.push(`${note.pairing}: present in token table but missing from contrast-notes.json`);
            continue;
        }
        if (stored.ratio !== note.ratio) {
            mismatches.push(
                `${note.pairing}: stored ratio ${stored.ratio} differs from computed ${note.ratio} (${note.pass ? 'pass' : 'fail'})`,
            );
        }
        if (stored.pass !== note.pass) {
            mismatches.push(
                `${note.pairing}: stored pass=${String(stored.pass)} differs from computed pass=${String(note.pass)}`,
            );
        }
    }

    // Check for pairings in the file that no longer exist in the token table.
    const computedLabels = new Set(computed.map((n) => n.pairing));
    for (const label of storedByLabel.keys()) {
        if (!computedLabels.has(label)) {
            mismatches.push(`${label}: present in contrast-notes.json but no longer in the pairing table`);
        }
    }

    if (mismatches.length > 0) {
        process.stderr.write('check-contrast-notes: contrast notes are stale — regenerate with:\n');
        process.stderr.write('  pnpm tsx scripts/generate-contrast-notes.ts\n\n');
        for (const m of mismatches) {
            process.stderr.write(`  ✗ ${m}\n`);
        }
        process.exitCode = 1;
        return;
    }

    process.stdout.write(`check-contrast-notes: ${computed.length} pairings match\n`);
}

if (path.resolve(process.argv[1] ?? '') === path.resolve(import.meta.filename)) {
    main().catch((error: unknown) => {
        process.stderr.write(`check-contrast-notes failed: ${String(error)}\n`);
        process.exitCode = 1;
    });
}
