/**
 * Golden-fixture generator — Feature 005 (T090) / Issue #131 (T-009).
 *
 * Runs the 1000-tick deterministic scenario, computes a SHA-256 hash
 * of the serialized output (frames + finalState), and writes a
 * TypeScript constant file at `tests/fixtures/determinism-golden-hash.ts`.
 *
 * The hash replaces the former 1.7 MB JSON blob: the test re-runs the
 * scenario and asserts the computed hash matches this constant.
 *
 * Usage: pnpm --filter @europa/console exec tsx scripts/generate-determinism-golden.ts
 */

import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { runDeterminismScenario, SCENARIO_TICKS } from '../tests/fixtures/determinism-scenario';

const OUT = resolve(
    import.meta.dirname,
    '..',
    'tests',
    'fixtures',
    'determinism-golden-hash.ts',
);

const run = runDeterminismScenario();

if (run.frames.length !== SCENARIO_TICKS) {
    throw new Error(
        `Expected ${SCENARIO_TICKS} frames, got ${run.frames.length}. ` +
            'The scenario definition may have changed.',
    );
}

const hash = createHash('sha256')
    .update(JSON.stringify(run.frames))
    .update(JSON.stringify(run.finalState))
    .digest('hex');

const contents = [
    '/**',
    ' * Auto-generated by scripts/generate-determinism-golden.ts — DO NOT EDIT.',
    ' *',
    ` * Hash of the full ${SCENARIO_TICKS}-tick determinism scenario output`,
    ' * (frames + finalState). Any change to the render pipeline will',
    ' * produce a different hash; regenerate after intentional changes.',
    ' */',
    "import { createHash } from 'node:crypto';",
    '',
    `// Regenerate: pnpm --filter @europa/console exec tsx scripts/generate-determinism-golden.ts`,
    `export const GOLDEN_HASH = '${hash}';`,
    `export const GOLDEN_TICKS = ${SCENARIO_TICKS};`,
    '',
].join('\n');

writeFileSync(OUT, contents, 'utf-8');
process.stdout.write(`golden hash: ${hash}\n`);
process.stdout.write(`wrote ${OUT} (${run.frames.length} frames hashed)\n`);
