/**
 * Branded Identity Generators — Feature 004
 *
 * Helpers for minting the wire protocol's opaque identifiers:
 * session tokens (seat claims, FR-007), connection ids (transport
 * handles), and player identifiers (FR-020/FR-021). Session tokens
 * and connection ids are 36-character v4 UUIDs produced by Node's
 * platform CSPRNG via the global `crypto.randomUUID()`. Player
 * identifiers are 12-character NanoID strings (alphanumeric, URL-safe)
 * generated via `crypto.getRandomValues`. No `uuid` package
 * dependency, no `Math.random`.
 *
 * Determinism discipline (constitution Principle II): these values
 * are *identity* artifacts, not simulation inputs. They never enter
 * engine state, tick math, or order application, so the byte-level
 * determinism guarantees (SC-001) are unaffected. The no-unseeded-
 * randomness rule governs simulation code; identity generation at a
 * trust boundary is exactly where unpredictability is required.
 *
 * Pure module apart from the CSPRNG call itself: no I/O, no clock
 * reads.
 */

import type { ConnectionId, PlayerId, SessionToken } from './contracts/network-types';

/**
 * Assert a plain string into a branded string type. The single place
 * the brand assertion happens; used at every trust boundary
 * (`generateSessionToken`, `generateConnectionId`, and future
 * `parseToken` / `parseMatchId` / `parseConnectionId` helpers).
 *
 * The cast is sound at the type level because the brand exists only
 * to prevent *accidental* interchange of distinct id kinds in user
 * code; this function is the deliberate, audited crossing point.
 *
 * @typeParam T - The branded target type (e.g., `SessionToken`).
 * @param value The raw string value.
 * @returns The same string, typed as `T`.
 */
export function toBranded<T extends string>(value: string): T {
    return value as T;
}

/**
 * Mint a fresh session token (36-char v4 UUID, branded
 * `SessionToken`). Issued when a seat is claimed (`joinAck`) and
 * presented again on reconnect (FR-007). Unpredictability matters:
 * tokens are bearer credentials for reclaiming a seat.
 *
 * @returns A new branded session token.
 */
export function generateSessionToken(): SessionToken {
    return toBranded<SessionToken>(crypto.randomUUID());
}

/**
 * Mint a fresh connection id (36-char v4 UUID, branded
 * `ConnectionId`). Assigned by the server when a WebSocket connects;
 * distinct from `SessionToken` so the transport handle can never be
 * confused with the seat claim it may later carry (see
 * `network-types.ts` on the two brands).
 *
 * @returns A new branded connection id.
 */
export function generateConnectionId(): ConnectionId {
    return toBranded<ConnectionId>(crypto.randomUUID());
}

// ---------------------------------------------------------------------------
// Player identifier generation (FR-020/FR-021)
// ---------------------------------------------------------------------------

/**
 * NanoID alphabet: uppercase + lowercase + digits (URL-safe).
 * 62 characters → ~5.95 bits per character; 12 chars ≈ 71 bits.
 */
const NANO_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';

/** Default player identifier length (12 characters). */
const DEFAULT_PLAYER_ID_LENGTH = 12;

/**
 * Mint a fresh player identifier (12-character NanoID, branded
 * `PlayerId`). Generated by the server at match start (FR-020/FR-021).
 * Independent of seat index; enables reconnect-by-id and
 * spectator-to-player promotion.
 *
 * Uses `crypto.getRandomValues` for cryptographic randomness — no
 * `Math.random`, no external NanoID package. 12-char alphanumeric
 * yields ~71 bits of entropy (62^12 ≈ 3.2 × 10^21 possibilities),
 * sufficient for match-scale collision resistance.
 *
 * Determinism note: intentionally NON-deterministic — PlayerIds are
 * identity artifacts generated at match start, not simulation inputs.
 *
 * @param length Number of characters (default 12; must be positive integer).
 * @returns A new branded `PlayerId` string.
 * @throws {RangeError} if length is not a positive integer.
 */
export function generatePlayerId(length: number = DEFAULT_PLAYER_ID_LENGTH): PlayerId {
    if (!Number.isInteger(length) || length <= 0) {
        throw new RangeError(`generatePlayerId length must be a positive integer, got ${String(length)}`);
    }
    const bytes = new Uint8Array(length);
    crypto.getRandomValues(bytes);
    let id = '';
    for (let i = 0; i < length; i++) {
        id += NANO_ALPHABET[(bytes[i] ?? 0) % NANO_ALPHABET.length];
    }
    return toBranded<PlayerId>(id);
}
